projetoies-1/mysite/costelaria/urls.py
from django.urls import path
from . import views

#Caminhos de path das urls

urlpatterns = [
     path('', views.index, name='index'),
     path('comandas/', views.ComandaListView.as_view(), name='Comandas'),
    path('comanda/<int:pk>',
         views.ComandaDetailView.as_view(), name='comanda-detail'),
    path('comanda/create/', views.ComandaCreate.as_view(), name='comanda-create'),
    path('comanda/<int:pk>/update/', views.ComandaUpdate.as_view(), name='comanda-update'),
    path('comanda/<int:pk>/delete/', views.ComandaDelete.as_view(), name='comanda-delete'),
]

projetoies-1/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('costelaria/', include('costelaria.urls')),
    path('', RedirectView.as_view(url='costelaria/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projetoies-1/mysite/costelaria/models.py
from django.db import models
from django.urls import reverse 

class Prato(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome 
    
    def get_absolute_url(self):
        return reverse('prato-detail', args=[str(self.id)])

class Bebida(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse("bebida-detail", kwargs={"pk": self.pk})
 
class Sobremesa(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse("sobremesa-detail", kwargs={"pk": self.pk})
    

class Comanda(models.Model):
    mesa = models.IntegerField(max_length=100, help_text='Escolha o número da mesa')
    prato = models.ManyToManyField(Prato, help_text='Selecione o prato')
    bebida = models.ManyToManyField(Bebida, help_text='Selecione a bebida')
    sobremesa = models.ManyToManyField(Sobremesa, help_text='selecione a sobremesa')

    def __init__(self):
        return self.mesa
    
    def get_absolute_url(self):
        return reverse("comanda-detail", kwargs={"pk": self.pk})

projetoies-1/mysite/costelaria/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Prato, Bebida, Sobremesa, Comanda


def index(request):
    num_comanda = ComandaInstance.objects.all()
    return render(
        request,
        'index.html',
        context={'num_comanda': num_comanda},
    )

#Visualizações do Prato

class PratoDetailView(generic.DetailView):
    model = Prato

#Visualização de Sobremesa

class SobremesaDetailView(generic.DetailView):
    model = Sobremesa

#Visualizações das Bebidas

class BebidaDetailView(generic.DetailView):
    model = Bebida

#Visualizações das comandas
class ComandaCreate(CreateView):
    model = Comanda
    fields = ['mesa', 'prato', 'sobremesa', 'bebida']


class ComandaUpdate(UpdateView):
    model = Comanda
    fields = ['mesa', 'prato', 'sobremesa', 'bebida']


class ComandaDelete(DeleteView):
    model = Comanda
    success_url = reverse_lazy('Comandas')

class ComandaListView(generic.ListView):
    model = Comanda
    paginate_by = 10

class ComandaDetailView(generic.DetailView):
    model = Comanda

projetoies-1/mysite/costelaria/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Menu Principal</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="background-color: rgb(183, 183, 183);">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

projetoies-1/mysite/costelaria/templates/costelaria/bebida_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div>
  <h1 class="display-5 text-center bg-warning p-3 m-2">Bebida: {{ bebida }} </h1>
</div>
<p class="text-center m-2"><em>{{bebida.date_of_birth}} - {% if bebida.date_of_death %}{{bebida.date_of_death}}{% endif %}</em></p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Bebidas</h4>

  <dl>
  {% for bebida in bebida.comanda_set.all %}
    <dt><a href="{% url 'comanda-detail' comanda.pk %}">{{comanda}}</a> ({{comanda.comandainstance_set.all.count}})</dt>
    <dd>{{comanda.summary}}</dd>
  {% endfor %}
  </dl>

</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/comanda_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-5 text-center bg-warning p-3 m-2">Deletar Comanda</h1>
<div class="text-center bg-warning">
  <h3 class="text-center m-4">Confirma em deletar comanda: {{ comanda.mesa }}?</h3>

  <form class="group-form" action="" method="POST" >
    {% csrf_token %}
    <input type="submit" class="btn btn-lg btn-warning btn-align-center btn-outline-dark" action="" value="Sim." />
    <a href="http://127.0.0.1:8000/costelaria/comandas/"><bottom type="button" class="btn btn-md btn-align-center btn-warning m-5 btn-outline-dark"><h4>Não!</h4></bottom></a>
  </form>
</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/comanda_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="bg-warning text-center p-3 m-2">
  <h1 class="text-center">Mesa: {{ comanda.mesa }}</h1>
</div>

<div class="bg-warning text-center w-50 mx-auto m-3">
  <div class="p-3 rounded border border-dark">
    <h4><strong>Bebidas:</strong> {{ comanda.prato }}</h4>
  </div>
  <div class="p-3 rounded border border-dark"><h4><strong>Bebidas:</strong> {{ comanda.bebida }}</h4></div> 
  <div class="p-3 rounded border border-dark"><h4><strong>Sobremesa:</strong> {{ comanda.sobremesa }}</h4></div>  
</div>

<div style="margin-left:20px;margin-top:20px" class="text-center">
  <a href="comanda/<int:pk>/update/"><bottom type="button" class="btn btn-lg btn-warning"><h3>Atualizar</h3></bottom></a>
  <a href="comanda/<int:pk>/delete/"><bottom type="button" class="btn btn-lg btn-warning"><h3>Encerrar</h3></bottom></a>

  <dl>
    {% for comanda in comanda.comanda_set.all %}
      <dt><a href="{% url 'comanda-detail' comanda.pk %}">{{comanda}}</a> ({{comanda.comandainstance_set.all.count}})</dt>
      <dd>{{comanda.summary}}</dd>
    {% endfor %}
  </dl>
    
</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/comanda_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container mt-5 align-items-center py-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <form class="group-form bg-warning" action="" method="post">
                <h1 class="text-center">Comanda</h1>
                <div class="form-group text-center p-2 m-2 bg-warning">
                    {% csrf_token %}
                    <table class="p-2 table">
                    {{ form.as_table }}
                    </table>
                    <input type="submit" value="Enviar" class="btn text-center btn-lg btn-warning btn-outline-dark btn-align-center" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/comanda_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="bg-warning text-center p-3 m-2">
  <h1 class="text-center">Lista de Comandas</h1>
</div>
{% if comanda_list %}
  <ul class="list-group">

  {% for comanda in comanda_list %}
    <li class="list-group-item list-group-item-action">
      <a href="{{ comanda.get_absolute_url }}" style="text-decoration:none">
      {{ comanda.mesa }}
      </a>
    </li>
  {% endfor %}
    
 </ul>
{% else %}
  <h2>Nenhuma Comanda Cadastrada.</h2>
{% endif %}
<div class="text-center">
  <a href="http://127.0.0.1:8000/costelaria/comanda/create/" class="text-center"><bottom type="button" class="btn btn-lg  mx-auto btn-align-center btn-warning m-5">Criar comanda!</bottom></a>
</div>   
        
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/prato_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-5 text-center bg-warning p-3 m-2">Prato: {{ author }} </h1>
<p class="text-center m-2">{{prato.date_of_birth}} - {% if prato.date_of_death %}{{prato.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Pratos</h4>

  <dl>
  {% for comanda in prato.comanda_set.all %}
    <dt><a href="{% url 'comanda-detail' comanda.pk %}">{{book}}</a> ({{comanda.comandainstance_set.all.count}})</dt>
    <dd>{{comanda.summary}}</dd>
  {% endfor %}
  </dl>

</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/costelaria/sobremesa_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-5 text-center bg-warning p-3 m-2">Sobremesa: {{ sobremesa }} </h1>
<p class="text-center m-2">{{sobremesa.date_of_birth}} - {% if sobremesa.date_of_death %}{{sobremesa.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Sobremesas</h4>

  <dl>
  {% for comanda in sobremesa.comanda_set.all %}
    <dt><a href="{% url 'comanda-detail' comanda.pk %}">{{comanda}}</a> ({{comanda.comandainstance_set.all.count}})</dt>
    <dd>{{comanda.summary}}</dd>
  {% endfor %}
  </dl>

</div>
{% endblock %}

projetoies-1/mysite/costelaria/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<body>
  <hr class="p-0 m-0 bg-black">
  <div>
    <h1 class="display-5 text-center bg-warning p-3 m-2">PORTAL SUL</h1>
  </div>
  <hr class="p-0 m-0 bg-black">
    <H3 class="text-center m-5">Seja Bem-vindo ao site da Costelaria Portal Sul</H3>
    <H3 class="text-center m-5">Desenvolvido pelos alunos da FATEC-SP!</H3>
    <!--<ul class="list-gorup p-2 mx-auto w-50 ">
      <li class="list-group-item p-3 rounded border border-dark"><h3><strong>Comandas:</strong></h3> {{ num_comanda }}</li>
      <li class="list-group-item p-3 rounded border border-dark"><h3><strong>Pratos:</strong></h3> {{ num_prato }}</li>
      <li class="list-group-item p-3 rounded border border-dark"><h3><strong>Sobremesas:</strong></h3> {{ num_sobremesa }}</li>
      <li class="list-group-item p-3 rounded border border-dark"><h3><strong>Bebidas:</strong></h3> {{ num_bebida }}</li>
    </ul>-->
  <div class="text-center">
    <a href="http://127.0.0.1:8000/costelaria/comandas/"><bottom type="button" class="btn btn-md btn-align-center btn-warning m-5 btn-outline-dark"><h4>Ir para tela de comandas!</h4></bottom></a>
 </div>
 <p>Caso queira ir para a tela de udpade, coloque a sequinte frase no navegador: http://127.0.0.1:8000/costelaria/comanda/id da comanda/update</p> 
 <p>Caso queira ir para a tela de delete, coloque a sequinte frase no navegador: http://127.0.0.1:8000/costelaria/comanda/id da comanda/delete</p>
</body>
    {% endblock %}